name: task_flow
description: "Task Flow application - Collaborate and Achieve"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  mailer: ^6.6.0
  http: ^1.6.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: any
  flutter_secure_storage: ^8.0.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.1.11
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/