name: task_manager
description: "A new Flutter project."
publish_to: 'none' 

version: 2.1.0+21

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  sqflite: ^2.4.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  dhis2_dart_utils: ^1.1.26
  fluttertoast: ^8.2.10
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/